kind: pipeline 
type: docker 
name: build jar

steps:
  - name: build
    image: gradle:jdk8
    commands:
      - gradle clean build

notifications:
  email:
    recipients: ed333.email@qq.com
    on_success: always
    on_failure: always
    