kind: pipeline 
type: docker 
name: build jar

steps:
- name: Checkout Git Repository
  uses: actions/checkout@v3
- name: Validate Gradle wrapper
  uses: gradle/wrapper-validation-action@v1
- name: Setup Gradle
  uses: gradle/gradle-build-action@v2
- name: Set up JDK
  uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
        java-version: '8'
- name: Configure Git User Details
  run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
- name: execute permission
  run: chmod +x gradlew
- name: Build Jar
  run: ./gradlew clean jar
- name: Upload Artifacts
  uses: actions/upload-artifact@v2
  with:
    name: Artifact
    path: build/libs/AdvancedAnnouncement-*.jar