kind: pipeline 
type: docker 
name: build jar

steps:
  - name: build
    image: gradle:jdk8
    commands:
      - gradle clean build
  - name: package
    image: gradle:jdk8
    commands:
    - tar -czvf project.tar.gz -C build/libs .
  - name: upload
    environment:
      USERNAME:
        from_secret: username
      ARTIFACT_DIR:
        from_secret: artifact_dir
      SCP_KEY:
        from_secret: key
    image: ubuntu
    commands:
    - apt-get update && apt-get install -y openssh-client
    - scp -i $SCP_KEY -o StrictHostKeyChecking=no project.tar.gz $USERNAME@43.143.62.103:$ARTIFACT_DIR/advanced_announcement


trigger:
  branch:
  - master
  event: 
    - push