kind: pipeline 
type: docker 
name: build jar

platform:
  os: linux
  arch: amd64
  variant: java8

steps:
  - name: build
    image: gradle:latest
    commands:
      - gradle clean build

notifications:
  email:
    recipients: ed333.email@qq.com
    on_success: always
    on_failure: always
    