# translations:
# zh_CN (简体中文) | en_US (English)
translation: zh_CN

# check update
# it will send update info when this plugin loaded
# or the server operator joined the server.
updateCheck: true

# update source for check update
# set to 0 is Gitee (faster for China user)
# set to 1 is GitHub
updateSource: 1

# use bStats to collect some information of your server.
# This information helps us to improve the plugin.
# Your information will be sent anonymously to bstats:
# https://bstats.org/plugin/bukkit/AdvancedAnnouncements/17508
bStats: true

# enables PlaceholderAPI support
PlaceholderAPI-support: true

# pre-announce time date format
date-format: yyyy-MM-dd HH:mm:ss

# random announcement used.
random: true

# debug, don't open unless it is necessary.
debug: false