# translations:
# zh_CN (简体中文) | en_US (English)
translation: zh_CN

# check update info
updateCheck: true

# use bStats to collect some information of your server
# This information helps us to improve the plugin.
bStats: true

# defines whether an announcement should be printed into console
# ONLY CHAT TYPE AND PRE_ANNOUNCE TYPE WILL BE DISPLAYED
Console-broadCast: true

# enables PlaceholderAPI support
PlaceholderAPI-support: true

# pre-announce time date format
date-format: yyyy-MM-dd HH:mm:ss

# random announcement used.
random: true

# debug test
debug: false